### ISSUE TITLE
please update package links

### ISSUE THREAD

**Issue by JeffreySarnoff** [gcalderone/ReusePatterns.jl#1]
https://github.com/JeffreySarnoff/TypedDelegation.jl

replaces both

https://github.com/JuliaArbTypes/TypedDelegation.jl (current version is at the above link)
https://github.com/Jeffrey-Sarnoff/Delegate.jl (unmaintained, probably obsolete)

thank you [and nice package]

**Comment by gcalderone** [comment]
Done! ;-)
