### ISSUE TITLE
Dataframes example does not seem to work in Julia 1.7.0?

### ISSUE THREAD

**Issue by rafael-guerra-www** [gcalderone/ReusePatterns.jl#2]
Hello Giorgio,

Tried the Dataframes example in: ReusePatterns.jl/examples/dataframes.jl
but it does not seem to work in Julia 1.7.0?

Thanks and rregards,
Rafael

**Comment by astrobc1** [comment]
I also get an error:

ERROR: LoadError: UndefVarError: rowtable not defined. The @forward macro seems to work on other use cases though.

Status `~/.julia/environments/v1.7/Project.toml`
  [a93c6f00] DataFrames v1.3.2
  [bd369af6] Tables v1.6.1

**Comment by gcalderone** [comment]
Fixed in v0.3.0.
