### ISSUE TITLE
Interation with DataStructures causes error

### ISSUE THREAD

**Issue by tbenst** [gcalderone/ReusePatterns.jl#3]
Thanks for this package! tracked down a subtle error/potential bug...
```julia
using DataStructures, HDF5, ReusePatterns

mutable struct DsetWrapper
    dset::HDF5.Dataset
end

@forward((DsetWrapper,:dset),HDF5.Dataset)
```
`ERROR: LoadError: cannot assign a value to variable DataStructures.list from module Main`

**Comment by gcalderone** [comment]
Fixed in v0.3.0.
