### ISSUE TITLE
Weird error with parametric types

### ISSUE THREAD

**Issue by mushunrek** [gcalderone/ReusePatterns.jl#7]
I ran into a version of the following minimal example:

```julia
using ReusePatterns

@quasiabstract AbstractTest{N, T}
    f::NTuple{N, T}
end

@quasiabstract AbstractTest2{N}
    f::NTuple{N, Number}
end

@quasiabstract Test <: AbstractTest{2, Number} end

@quasiabstract Test2 <: AbstractTest2{2} end
```
Then, `Test( (1, 1.0) )` produces an error, while `Test2( (1, 1.0) )` does not, although they should give the exact same thing. The exact error is 
```
TypeError: in new, expected Tuple{Vararg{T, N}} where {N, T}, got a value of type Tuple{Int64, Float64}
```

**Comment by gcalderone** [comment]
Please have a look to the Julia manual concerning parametric types and test your code before submitting issues.
Comments:
- you missed the `struct` keyword, your code will raise errors well before the last line;
- In your first case, the actual value for `T` in `NTuple{N, T}` is inferred from the constructor, with the only constraint that `T <: Number`.  When you invoke `Test(  (1, 1.0) )` you imply `T` must simultaneously be an `Int64` and a `Float64` which is impossible, hence the error;
   - you can fix this by explicitly defining an inner constructor forcing `T` to be `Number`, i.e.:
    ```
    @quasiabstract struct Test <: AbstractTest{2, Number}
        Test(args...) = AbstractTest{2, Number}(args...)
    end
    ```
- In your second case, you fix `T` to be `Number` already in the definition of `AbstractTest2`, hence the types used in the constructor are irrelevant (as long as they are `<: Number`).
